gradebook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gradesbook', include('gradesbook.urls')),
]

gradesbook/urls.py
from django.urls import path
from . import views

app_name = 'gradesbook'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='homepage'),
    path('/manager', views.ManagerPanelView.as_view(), name='manager'),
    path('/manager/creaateschoolclass', views.CreateSchoolClassView.as_view(),
         name='create_school_class'),
    path('/manager/editschoolclass/<str:class_unique_code>',
         views.EditSchoolClassView.as_view(), name='edit_school_class'),
    path('/manager/delstudent/<int:user_id>',
         views.DeleteStudentView.as_view(), name='del_student'),
    path('/manager/deactivationschoolclass/<str:class_unique_code>',
         views.DeactivationSchoolClassView.as_view(),
         name='deactivation_school_class'),
    path('/manager/activationschoolclass/<str:class_unique_code>',
         views.ActivationSchoolClassView.as_view(),
         name='activation_school_class'),
    path('/manager/deactivationteacher/<str:teacher_user_id>',
         views.DeactivationTeacherView.as_view(),
         name='deactivation_teacher'),
    path('/manager/activationteacher/<str:teacher_user_id>',
         views.ActivationTeacherView.as_view(),
         name='activation_teacher'),
    path('/manager/addteacher', views.AddTeacherView.as_view(),
         name='add_teacher'),
    path('/manager/editschoolclass/<str:class_unique_code>/addsubject',
         views.AddSubjectView.as_view(), name='add_subject'),
    path('/manager/editstudent/<int:user_id>',
         views.ManagerStudentEditView.as_view(), name='manager_student_edit'),
    path('/manageresetusesr/<int:prefix>/<int:user_id>',
         views.ManagerResetUserView.as_view(), name='manager_reset_user'),
    path('/manager/editschoolclass/<str:class_unique_code>/'
         '<str:subject_unique_code>', views.ManagerSubjectView.as_view(),
         name='subject_view'),
    path('/manager/deldate/<str:class_unique_code>/<str:subject_unique_code>'
         '/<int:day>/<int:lesson>', views.DeleteSubjectDateView.as_view(),
         name='delete_date'),
    path('/manager/delsubject/<str:class_unique_code>/'
         '<str:subject_unique_code>', views.DeleteSubjectView.as_view(),
         name='del_subject'),
    path('/delsubjectteacher/<str:class_unique_code>/' +
         '<str:subject_unique_code>/<int:teacher_user_id>',
         views.DeleteSubjectTeacherView.as_view(), name='del_subject_teacher'),
    path('/addnewsubjectteacher/<str:class_unique_code>/' +
         '<str:subject_unique_code>',
         views.AddSubjectTeacherView.as_view(), name='add_subject_teacher'),
    path('/manager/teacher/<str:teacher_user_id>',
         views.ManagerTeacherView.as_view(), name='manager_teacher'),
    path('/manager/editteacher/<int:user_id>',
         views.ManagerTeacherEditView.as_view(), name='manager_teacher_edit'),
    path('/manager/delteacher/<str:teacher_user_id>',
         views.ManagerDeleteTeacherView.as_view(), name='manager_del_teacher'),
    path('/teacher', views.TeacherPanelView.as_view(), name='teacher'),
    path('/teachersubject/<str:subject_unique_code>',
         views.TeacherSubjectView.as_view(), name='teacher_subject'),
    path('/timetable/<str:person>', views.TimetableView.as_view(),
         name='timetable'),
    path('/mailbox', views.MailboxView.as_view(), name='mailbox'),
    path('/mailtext/<int:mailbox_id>/<int:mailbox_type>',
         views.MailTextView.as_view(), name='mail_text'),
    path('/studentparent', views.StudentParentView.as_view(),
         name='student_parent'),
    path('/firstlogin', views.FirstLoginView.as_view(), name='first_login'),
    path('/logout', views.LogOutView.as_view(), name='logout'),
    path('/createmessage/<int:prefix>/<str:code>',
         views.CreateMessageView.as_view(), name='create_message'),
    path('/manager/student/<int:user_id>', views.ManagerStudentView.as_view(),
         name='manager_student'),
]

gradesbook/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.views import View
from django.views.generic import TemplateView, FormView
from django.views.generic.edit import FormMixin, ProcessFormView
from django.core.exceptions import FieldError, ObjectDoesNotExist
from django.db import IntegrityError, transaction, DataError
from django.core.paginator import Paginator
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from .models import *
from .permissions import *
from .forms import *

class BaseView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        unread = MailboxReceived.objects.filter(
            recipient__user=self.request.user,
            read=False
        )
        context['unread'] = len(unread)
        try:
            context['username'] = self.request.session['user']
        except KeyError:
            context['username'] = None
        return context


class HomepageView(FormView):
    template_name = 'gradesbook/homepage.html'
    form_class = LoginForm

    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data())

    def get_success_url(self):
        user_permission = list(self.request.user.get_all_permissions())[0]
        if user_permission == 'gradesbook.student':
            return reverse('gradesbook:student_parent')
        elif user_permission == 'gradesbook.parent':
            return reverse('gradesbook:student_parent')
        elif user_permission == 'gradesbook.teacher':
            return reverse('gradesbook:teacher')
        elif user_permission == 'gradesbook.manager':
            return reverse('gradesbook:manager')
        else:
            raise ValueError("Unknown permission")

    def form_valid(self, form):
        try:
            User.objects.get(username=form.cleaned_data['username'])
        except User.DoesNotExist:
            # User doesnt exist
            return render(
                self.request, 'gradesbook/homepage.html',
                {'form': form, 'user_no_exist': True}
            )
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        if user is not None:
            login(self.request, user)
        else:
            # Wrong password
            return render(
                self.request,
                'gradesbook/homepage.html',
                {'form': form, 'wrong_password': True}
            )
        self.request.session['user'] = f'{self.request.user.first_name} ' \
                                       f'{self.request.user.last_name}'
        return super().form_valid(form)


class LogOutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            request.session['user'] = None
        return HttpResponseRedirect(reverse('gradesbook:homepage'))


class FirstLoginView(LoginRequiredMixin, UserPassesTestMixin, ProcessFormView,
                     FormMixin, BaseView):
    template_name = 'gradesbook/firstlogin.html'
    form_class = FirstLoginForm
    permission = {
        'gradesbook.student': Student,
        'gradesbook.parent': Parent,
        'gradesbook.teacher': Teacher
    }

    def test_func(self):
        test = False
        if self.request.user.has_perm('gradesbook.student') \
                or self.request.user.has_perm('gradesbook.parent') \
                or self.request.user.has_perm('gradesbook.teacher'):
            test = True
        return test

    def get_success_url(self):
        user_permission = list(self.request.user.get_all_permissions())[0]
        if user_permission == 'gradesbook.student':
            self.request.session['user'] = get_object_or_404(
                Student,
                user=self.request.user
            ).__str__()
            return reverse('gradesbook:student_parent')
        elif user_permission == 'gradesbook.parent':
            self.request.session['user'] = get_object_or_404(
                Parent,
                user=self.request.user
            ).__str__()
            return reverse('gradesbook:student_parent')
        elif user_permission == 'gradesbook.teacher':
            self.request.session['user'] = get_object_or_404(
                Teacher,
                user=self.request.user
            ).__str__()
            return reverse('gradesbook:teacher')
        elif user_permission == 'gradesbook.manager':
            self.request.session['user'] = self.request.user.username
            return reverse('gradesbook:manager')
        else:
            raise ValueError("Unknown permission")

    def get_initial(self):
        initial = super().get_initial()
        username = self.request.user.username
        initial['username'] = username
        return initial

    def form_valid(self, form):
        user = self.request.user
        with transaction.atomic():
            if form.cleaned_data['username'] != user.username:
                try:
                    user.username = form.cleaned_data['username']
                    user.save()
                except IntegrityError:
                    return render(
                        self.request,
                        'gradesbook/firstlogin.html',
                        {'form': form, 'user_taken': True, }
                    )
            if form.cleaned_data['password'] == \
                    form.cleaned_data['password_confirm']:
                try:
                    user.set_password(form.cleaned_data['password'])
                    user.save()
                    login(self.request, user)
                except IntegrityError:
                    raise Http404('Password problem.')
            else:
                return render(
                    self.request,
                    'gradesbook/firstlogin.html',
                    {'form': form, 'pass_no_confirm': True, }
                )
            user_permission = list(self.request.user.get_all_permissions())[0]
            person = get_object_or_404(
                self.permission[user_permission],
                user=user
            )
            person.first_login = False
            person.save()
        return super().form_valid(form)


class ManagerPanelView(LoginRequiredMixin, UserPassesTestMixin, BaseView):
    template_name = 'gradesbook/manager.html'
    inactive_school_classes = None
    inactive_teachers = None

    def test_func(self):
        return self.request.user.has_perm('gradesbook.manager')

    def post(self, request, **kwargs):
        try:
            if request.POST['inactive_class'] == 'on':
                self.inactive_school_classes = \
                    SchoolClass.objects.filter(active=False).order_by('-year')
            else:
                self.inactive_school_classes = None
            return super(ManagerPanelView, self).render_to_response(
                self.get_context_data(**kwargs)
            )
        except KeyError:
            try:
                if request.POST['inactive_teachers'] == 'on':
                    self.inactive_teachers = \
                        Teacher.objects.filter(active=False).order_by('name')
                else:
                    self.inactive_teachers = None
                return super(ManagerPanelView, self).render_to_response(
                    self.get_context_data(**kwargs)
                )
            except KeyError:
                return HttpResponseRedirect(
                    self.request.META.get('HTTP_REFERER')
                )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['classes'] = SchoolClass.objects.filter(
            active=True
        ).order_by('name')
        context['ia_classes'] = self.inactive_school_classes

        students = {}
        for my_class in context['classes']:
            all_students = Student.objects.filter(school_class=my_class)
            students[my_class] = all_students
        context['students'] = students

        context['teachers'] = Teacher.objects.filter(
            active=True
        ).order_by('name')
        context['ia_teachers'] = self.inactive_teachers
        return context


class CreateSchoolClassView(LoginRequiredMixin, UserPassesTestMixin,
                            ProcessFormView, FormMixin, BaseView):
    template_name = 'gradesbook/managercreateschoolclass.html'
    form_class = SchoolClassForm

    def test_func(self):
        return self.request.user.has_perm('gradesbook.manager')

    def get_success_url(self):
        return reverse('gradesbook:manager')

    def form_valid(self, form):
        # Method is called only when data is valid
        current_class = form.save(commit=False)
        current_class.unique_code = f'{form["name"].value()}' \
                                    f'{form["year"].value()}'
        current_class.save()
        return super().form_valid(form)


class EditSchoolClassView(LoginRequiredMixin, UserPassesTestMixin,
                          ProcessFormView, FormMixin, BaseView):
    template_name = 'gradesbook/managereditschoolclass.html'
    form_class = CreateStudentForm

    def test_func(self):
        return self.request.user.has_perm('gradesbook.manager')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = Student.objects.filter(
            school_class__unique_code=self.kwargs['class_unique_code']

gradesbook/templates/gradesbook/base.html
<head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'gradesbook/style.css' %}">
  <link rel="stylesheet" href="{% static 'gradesbook/css/bootstrap.min.css' %}">
  <script src="{% static 'gradesbook/jquery-3.4.1.js' %}"></script>
  <script src="{% static 'gradesbook/popper.min.js' %}"></script>
  <script src="{% static 'gradesbook/js/bootstrap.min.js' %}"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <link rel="icon" href="data:,">

  <title>Класний журнал</title>
</head>
<body>
  <header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="col-10">
        <span><i class="material-icons" style="font-size:35px;"> face </i>  </span>
        <span class="login" style="font-size:25px;">{{username}}</span>
      </span>
      <span class="col-1">
        <a class="navbar-brand mailbox" href="{% url 'gradesbook:mailbox' %}">
          <i class="material-icons align-text-bottom" style="font-size:45px;">mail_outline</i>
          <span style="font-size:22px;"><b>{{unread}}</b></span>
        </a>
      </span>
      <span class="col-1">
        <a class="navbar-brand logout" href="{% url 'gradesbook:logout' %}" style="font-size:22px;"> <b>Вихід</b>
          <i class="material-icons align-text-bottom" style="font-size:25px;"> arrow_forward </i>
        </a>
      </span>
    </nav>
  </header>
  {%block grades %}
  {%endblock%}
</body>

gradesbook/templates/gradesbook/manager.html
{% extends 'gradesbook/base.html' %}
<head>
  {% load gradesbooktags %}
</head>
{% block grades%}
  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          
          <div class="row">
            <div class="col-5">
              <h3>АКТИВНІ КЛАСИ:</h3>
              <br>
              {% for class in classes %}
                <div class="row">
                  <span>
                    <b style="font-size:25px;">{{class}}</b>
                    <i class="material-icons align-text-bottom" style="font-size:23px;">person</i>{% with temp=students|key_value:class%} {% elements_number temp %}{% endwith %}
                  </span>
                  <span style=" margin-left:10px;">
                    <a class="btn btn-secondary" href="{% url 'gradesbook:edit_school_class' class.unique_code %}">РЕДАГУВАТИ КЛАС</a>
                    <a class="btn btn-secondary" data-toggle="tooltip" title="Надіслати повідомлення здобувачам освіти" href="{%url 'gradesbook:create_message' 1 class.unique_code %}"><i class="material-icons align-text-bottom" style="font-size:25px;">mail</i></a>
                    <a class="btn btn-secondary" data-toggle="tooltip" title="Надіслати повідомлення батькам" href="{%url 'gradesbook:create_message' 2 class.unique_code %}"><i class="material-icons align-text-bottom" style="font-size:25px; color:#FED65E;">mail</i></a>
                  </span>
                </div>
                <hr>
              {% endfor %}
              <br>
              <br>
              <span id="mclasses"></span>
              <a class="btn btn btn-outline-dark" id="classes" href="{%url 'gradesbook:create_school_class' %}"><b>ДОДАТИ НОВИЙ КЛАС</b></a>
              <br><br>
              {% if ia_classes is not None %}
                <script>
                  window.location.hash = '#mclasses';
                </script>
                <form action="{%url 'gradesbook:manager' %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="inactive_class" value='off'>
                  <button class="btn btn-outline-secondary text-center" type="submit"><b>ПРИХОВАТИ НЕАКТИВНІ КЛАСИ</b></button>
                </form>
                {% for class in ia_classes %}
                  <div class="row">
                    <b>{{class.name}} ({{class.unique_code}}) </b> &nbsp;&nbsp;
                    <a class="btn btn-secondary" href="{% url 'gradesbook:edit_school_class' class.unique_code %}">РЕДАГУВАТИ КЛАС</a>
                  </div>
                  <br>
                {% endfor %}
              {% else %}
                <form action="{%url 'gradesbook:manager' %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="inactive_class" value='on'>
                  <button class="btn btn btn-outline-dark text-center" type="submit"><b>ПОКАЗАТИ НЕАКТИВНІ КЛАСИ</b></button>
                </form>
              {% endif %}
            </div>
            <div class="col-7">
              <h3> ВИКЛАДАЧІ: </h3>
              <br>
              {% for teacher in teachers %}
                <div class="row">
                  <div class="col-5">
                    <b style="font-size:20px;">{{teacher}}</b>
                  </div>
                  <div class="col-2 ">
                    <a class="btn btn-secondary" data-toggle="tooltip" title="Надіслати повідомлення викладачу" href="{% url 'gradesbook:create_message' 7 teacher.user.id %}"><i class="material-icons align-text-bottom" style="font-size:25px; color: #F7E2FE">mail</i></a>
                  </div>
                  <div class="col-4">
                    <a class="btn btn-secondary" style="font-size:14px;" href="{% url 'gradesbook:manager_teacher' teacher.user.id %}"> інформація та редагування</a>
                  </div>
                  <div class="col-1">
                    <a class="btn btn-secondary" style="font-size:14px;" href="{% url 'gradesbook:deactivation_teacher' teacher.user.id %}">деактивувати</a>
                  </div>
                </div>
                <br>
                <div class="row">
                  {% if teacher.first_login is True %}
                    <div class="col-8">
                      <i class="material-icons align-text-bottom" style="font-size:20px;">close</i>
                      Ніразу не здійснив вхід<br>
                      ім'я користувача: {{teacher.user.username}}<br>
                      пароль: {{teacher.user.username}}234
                    </div>
                    <div class="col-4">
                      <a class="btn btn btn-outline-dark" style="font-size:14px;" href="{%url 'gradesbook:manager_reset_user' 234 teacher.user.id %}">Скинути дані для входу</a>
                    </div>
                  {% else %}
                    <div class="col-8">
                      <i class="material-icons align-text-bottom" style="font-size:20px;">check</i>
                      Здійснив перший вхід - було персоналізовано обліковий запис
                    </div>
                    <div class="col-4">
                      <a class="btn btn btn-outline-dark" style="font-size:14px;" href="{%url 'gradesbook:manager_reset_user' 234 teacher.user.id %}">Скинути дані для входу</a>
                    </div>
                  {% endif %}
                </div>
                <br>
                <hr>
              {% endfor %}
              <br>
              <div class="row" id="teachers">
                <a class="btn btn-outline-dark" href="{% url 'gradesbook:add_teacher' %}"><b>ДОДАТИ ВИКЛАДАЧА</b></a> <br>
              </div>
              <br>
              {% if ia_teachers is not None %}
                <script>
                  window.location.hash = '#teachers';
                </script>
                <div class="row">
                  <form action="{%url 'gradesbook:manager' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="inactive_teachers" value='off'>
                    <button class="btn btn-outline-secondary text-center" type="submit"><b>ПРИХОВАТИ НЕАКТИВНИХ ВЧИТЕЛІВ</b></button>
                  </form>
                </div>
                <br>
                <div class="row">
                  {% for teacher in ia_teachers %}
                    <div class="col-5">
                      <b>{{teacher}}</b>
                    </div>
                    <div class="col-7">
                      <div class="row">
                      <a class="btn btn-secondary" style="font_size: 14px;" href="{% url 'gradesbook:activation_teacher' teacher.user.id %}"> <span style="font-size: 16px;">АКТИВУВАТИ ВИКЛАДАЧА</span></a>
                      </div>
                      <br>
                    </div>
                  {% endfor %}
                </div>
              {% else %}
                <div class="row">
                  <form action="{% url 'gradesbook:manager' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="inactive_teachers" value='on'>
                    <button class="btn btn btn-outline-dark text-center" type="submit"><b>ВІДОБРАЗИТИ НЕАКТИВНИХ ВИКЛАДАЧІВ</b></button>
                  </form>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
  <script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
    });
  </script>
{% endblock %}

gradesbook/templates/gradesbook/manageraddsubjectteacher.html
{% extends 'gradesbook/base.html' %}

{% block grades%}
  <body>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="row">
              <h4>Додати викладача предмету <b> {{subject}} </b> в класі <b> {{class}} </b> :</h4>
            </div>
            <br><br>
            <form action="{%url 'gradesbook:add_subject_teacher' class.unique_code subject.unique_code %}" method="POST">
              {% csrf_token %}
              {% for teacher in form.teachers %}
                <b>{{teacher}}</b><br>
              {% endfor %}
              <br>
              <button class="btn btn-outline-secondary" type="submit"><b>ДОДАТИ ВИКЛАДАЧА</b></button>
              <br>
            </form>
            <br>
            <a class="btn btn-secondary logout2" href="{%url 'gradesbook:subject_view' class.unique_code subject.unique_code %}">СКАСУВАТИ</a>
          </div>
        </div>
      </div>
  </body>
{% endblock %}

gradesbook/templates/gradesbook/manageraddteacher.html
{% extends 'gradesbook/base.html' %}

{% block grades%}
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 login my-auto">
      <form action="{% url 'gradesbook:add_teacher' %}" method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="col-6 offset-3">
            {{form}}
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-4 offset-4">
            <button type="submit" class="btn btn-outline-secondary text-center"><b>ДОДАТИ ВИКЛАДАЧА</b></button>&nbsp;
            <a class="btn btn-secondary logout2" href="{%url 'gradesbook:manager' %}">СКАСУВАТИ</a>
          </div>
        </div>
      </form>
      <br>
      </div>
    </div>
  </div>
</body>
{% endblock %}

gradesbook/templates/gradesbook/managereditschoolclass.html
{% extends 'gradesbook/base.html' %}

{% block grades%}
  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 login my-auto">
          <div class="row">
            {% if current_class.active == True %}
            <div class="col-2">
              <h5>КЛАС <b>{{current_class}}</b> (АКТИВНИЙ) </h5>
              <br>
            </div>
              <div class="col-10">
                <form action="{% url 'gradesbook:deactivation_school_class' current_class.unique_code %}" method="POST">
                  {% csrf_token %}
                  <button class="btn btn-outline-secondary " type="submit"><b>ДЕЗАКТИВАЦІЯ</b></button> &nbsp; &nbsp;
                  <a class="btn btn-outline-secondary" href="{%url 'gradesbook:manager' %}"><b>ПОВЕРНУТИСЯ ДО ПАНЕЛІ АДМІНІСТРАТОРА</b></a>
                </form>
              </div>
            {% else %}
              <div class="col-2">
                <h5>КЛАС <b>{{current_class}}</b> (НЕАКТИВНИЙ)</h5>
                <br>
              </div>
              <div class="col-10">
                <form action="{% url 'gradesbook:activation_school_class' current_class.unique_code %}" method="POST">
                  {% csrf_token %}
                  <button class="btn btn-outline-secondary " type="submit"><b>АКТИВАЦІЯ</b></button>
                  <a class="btn btn-outline-secondary" href="{%url 'gradesbook:manager' %}"><b>Закінчити редагування класу</b></a>
                </form>
              </div>
            {% endif %}
          </div>
            <br><br>
          <div class="row">
            <div class="col-8">
              <h3>Список здобувачів освіти:</h3> <br><br>
              {% for student in students %}
                <div class="row">
                  <div class="col-4">
                    <b style="font-size:20px;">{{forloop.counter}}. {{student}}</b>
                  </div>
                  <div class="col-4"><a class="btn btn-secondary" href="{%url 'gradesbook:manager_student' student.user.id %}">інформація про здобувача освіти і оцінки</a></div>
                  <div class="col-4"><a class="btn btn-secondary" onclick="return confirm('Ви впевнені, що хочете видалити цього здобувача освіти')" href="{%url 'gradesbook:del_student' student.user.id %}">Видалити здобувача освіти</a></div>
                </div>
                <br>
                <div class="row">
                  {% if student.first_login is not False %}
                    <div class="col-8">
                      Не здійснив вхід<br>
                      <u>Ім'я користувача</u>: {{student.user.username}}
                      <br><u>Пароль</u>: {{student.user.username}}123
                    </div>
                    <div class="col-4">
                      <a class="btn btn-secondary" href="{%url 'gradesbook:manager_reset_user' 123 student.user.id %}">Скинути дані для входу</a>
                    </div>
                  {% else %}
                    <div class="col-8">
                      Здійснив перший вхід - персоналізовано обліковий запис
                    </div>
                    <div class="col-4">
                      <a class="btn btn-secondary" href="{%url 'gradesbook:manager_reset_user' 123 student.user.id %}">Скинути дані для входу</a>
                    </div>
                  {% endif %}
                </div>
                <br><hr>
              {% endfor %}
              <br><br>
                <h4>ДОДАТИ НОВОГО УЧНЯ ДО КЛАСУ:</h4><br>
                <form action="{% url 'gradesbook:edit_school_class' current_class.unique_code %}" method="POST">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-4">
                      {{form.name.label}}{{form.name}}<br>
                      {{form.surname.label}}{{form.surname}}<br>
                      {{form.birthday.label}}{{form.birthday}}<br>
                    </div>
                    <div class="col-4">
                      <b>Дані одного з батьків:</b><br>
                      {{form.first_parent_name.label}}{{form.first_parent_name}}<br>
                      {{form.first_parent_surname.label}}{{form.first_parent_surname}}<br>
                    </div>
                    <div class="col-4">
                      <b>Дані ще одного з батьків (необов'язково):</b><br>
                      {{form.second_parent_name.label}}{{form.second_parent_name}}<br>
                      {{form.second_parent_surname.label}}{{form.second_parent_surname}}<br>
                    </div>
                  </div>
                  <br>
                  <div class="row">
                    <button class="btn btn-outline-secondary" type="submit"><b>ДОДАТИ УЧНЯ ДО КЛАСУ</b></button>
                  </div>
                  <br>
                  <div class="row">
                    <a class="btn btn-outline-secondary" href="{%url 'gradesbook:manager' %}"><b>ЗАКІНЧИТИ РЕДАГУВАННЯ КЛАСУ</b></a>
                  </div>
                </form>
              <br><br>
            </div>
            <div class="col-4">
              <h4>ПРЕДМЕТИ:</h4><br>
              <div class="row">
              {% for subject in subjects %}
                <div class="col-5">
                  {{subject}}
                </div>
                <div class="col-5">
                  <a class="btn btn btn-outline-dark" href="{%url 'gradesbook:subject_view' current_class.unique_code subject.unique_code %}">про предмет</a>
                </div>
                <div class="col-2">
                  <a class="btn btn btn-outline-dark" onclick="return confirm('Ви впевнені, що хочете видалити цей предмет?')" href="{%url 'gradesbook:del_subject' current_class.unique_code subject.unique_code %}"> видалити</a>
                </div>
                <br><hr>
              {% endfor %}
              </div>
              <br>
              <a class="btn btn-outline-dark" style="font-size:20px;" href="{%url 'gradesbook:add_subject' current_class.unique_code %}">ДОДАТИ НОВІ ПРЕДМЕТИ</a>
            </div>
          </div>
          <br>
        </div>
      </div>
    </div>
  </body>
{% endblock %}